spring:
  application:
    name: CUSTOMER-SERVICE

  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: https://n5-subprj-cloudserver.herokuapp.com/

resilience4j:
  ratelimiter:
    instances:
      multiRate:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 2s

  retry:
    instances:
      basic:
        maxRetryAttempts: 3
        waitDuration: 8s