server:
  port: ${PORT:8081}

spring:
  application:
    name: CUSTOMER-SERVICE

eureka:
  instance:
    hostname: n5-subprj-customer.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}

resilience4j:
  ratelimiter:
    instances:
      multiRate:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s

#  retry:
#    instances:
#      basic:
#        maxRetryAttempts: 5
#        waitDuration: 8s